#!perl
use strict;
use utf8;
use File::Spec;
use File::Basename;
use lib File::Spec->catdir(dirname(__FILE__), '../lib');
use Plack::Builder;

use PerlToolbox::Web;
use PerlToolbox;
use Plack::Session::Store::File;
use Plack::Session::State::Cookie;
use URI::Escape;
use File::Path ();

my $session_dir = File::Spec->catdir(File::Spec->tmpdir, uri_escape("PerlToolbox") . "-$<" );
File::Path::mkpath($session_dir);
my $app = builder {
    enable 'Plack::Middleware::Static',
        path => qr{^(?:/static/)},
        root => File::Spec->catdir(dirname(__FILE__), '..');
    enable 'Plack::Middleware::Static',
        path => qr{^(?:/robots\.txt|/favicon\.ico)$},
        root => File::Spec->catdir(dirname(__FILE__), '..', 'static');
    enable 'Plack::Middleware::ReverseProxy';
    enable 'Plack::Middleware::AccessLog';

    # If you want to run the app on multiple servers,
    # you need to use Plack::Sesion::Store::DBI or ::Store::Cache.
    enable 'Plack::Middleware::Session',
        store => Plack::Session::Store::File->new(
            dir => $session_dir,
        ),
        state => Plack::Session::State::Cookie->new(
            httponly => 1,
        );

    PerlToolbox::Web->to_app();
};
unless (caller) {
    my $port        = 5000;
    my $host        = '127.0.0.1';
    my $max_workers = 4;
    my $loader;

    require Getopt::Long;
    my $p = Getopt::Long::Parser->new(
        config => [qw(posix_default no_ignore_case auto_help)]
    );
    $p->getoptions(
        'p|port=i'      => \$port,
        'host=s'      => \$host,
        'max-workers' => \$max_workers,
        'version!'    => \my $version,
        'r|reload'     => sub { $loader ||= do { require Plack::Loader::Restarter; Plack::Loader::Restarter->new() } },
        'R|Reload=s'   => sub { $loader ||= do { require Plack::Loader::Restarter; Plack::Loader::Restarter->new() };  $loader->watch(split ",", $_[1]) },
        'c|config=s'  => \my $config_file,
    );
    if ($version) {
        print "PerlToolbox: $PerlToolbox::VERSION\n";
        exit 0;
    }
    if (!$loader) {
        require Plack::Loader;
        $loader = Plack::Loader->new();
    }
    if ($config_file) {
        my $config = do $config_file;
        Carp::croak("$config_file: $@") if $@;
        Carp::croak("$config_file: $!") unless defined $config;
        unless ( ref($config) eq 'HASH' ) {
            Carp::croak("$config_file does not return HashRef.");
        }
        no warnings 'redefine';
        *PerlToolbox::load_config = sub { $config }
    }

    print "PerlToolbox: http://${host}:${port}/\n";

    my $server = $loader->load('Starlet',
        port        => $port,
        host        => $host,
        max_workers => $max_workers,
    );
    $loader->preload_app(sub { warn "LOAD"; warn __FILE__; Plack::Util::load_psgi(__FILE__) });
    $loader->run($server);
    exit 0;
}
warn "Return app";
return $app;
